### ISSUE TITLE
Latest master does not work for me

### ISSUE THREAD

**Issue by certik** [hashdist/hashdist#129]
```
$ hit build
Unpacking sources files:uqndh6v3lidspbha4ssa5ezz2fiazowy
Unpacking sources tar.gz:er2ptudqnndwzyhbhemvzq23gyfnwzs5
[distribute] Building aw75hh2gzghk.., follow log with:
[distribute]   tail -f /tmp/distribute-aw75hh2gzghk/build.log
[distribute ERROR] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 1
[distribute ERROR] command failed (code=1); raising
```

I followed the instructions, and I modified my `config.yaml`:

```
## Configuration file for Hashdist

## All relative paths are relative to the directory containing this
## configuration file.

## Where to store the built software

build_stores:
 - dir: /tmp/bld


## Location where temporary directories for building software are created.
## Such directories are by default removed again once the build is done.

build_temp: /tmp


## Locations of downloaded tarballs and git repositories.  A location
## can either be a local filesystem, or a URL to an online, read-only
## mirror. Only the first location, which should be a local directory,
## will be written to.

source_caches:
 - dir: /tmp/src
## For additional source cache mirror:
## - url: https://some.server.org/hashdist/src


## The cache directory is used for misc. caching (e.g., probing of host
## system).  The contents can always be wiped without resulting in rebuilds.

cache: /tmp/cache

## The roots directory contains links to (links to) profiles. Anything
## pointed to through here will not be deleted when garbage-collected.

gc_roots: /tmp/gcroots
```
