### ISSUE TITLE
launcher:Unable to launch './test-python/bin/python2.7.real' (No such file or directory)

### ISSUE THREAD

**Issue by johannesring** [hashdist/hashdist#220]
Running `python` (when `host: true`) on Cygwin results in the following error:

```
$ ./test-host-python/bin/python
launcher:Unable to launch './test-host-python/bin/python2.7.real' (No such file or directory)
```

The profile `test-host-python.yaml` looks like this:

```
extends:
- file: cygwin.yaml

packages:
  launcher:
  python:
    host: true
```
