### ISSUE TITLE
default profile values, and default use packages

### ISSUE THREAD

**Issue by ahmadia** [hashdist/hashdist#243]
I'm 50% of the way towards implementing default profile settings in hashdist.

This means that your `config.yaml` (you can have more than one of these) specifies a default set of build parameters, that are then overridden by your profiles.  Why is this useful?  It allows us to provide os-agnostic build profiles.  The builds are still hashed, and if you wanted to be extra careful, you could remove the default profile (to ensure complete reproducibility), but this will go a long way towards making it easy to install profiles that somebody built or tested on another operating system, and remove the need to specify multiple build profiles to build the same package on multiple operating systems.

Here's what a sample config.yaml might contain:

```
default_profile:
  package_dirs:
    - pkgs
    - base

  hook_import_dirs:
    - base

  parameters:
    platform: Darwin
    pyver: '2.7'  # as in used in lib/pythonX.Y/site-packages
    python_site_packages_rel: 'lib/python2.7/site-packages'
    python_host_packages: '/Library/Python/2.7/site-packages'
    use_python_host_packages: false

    BASH: /bin/bash
    PATH: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
    PROLOGUE: |
      export MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion | sed "s/\(10.[0-9]\).*/\1/")

  if_needed:
    blas:
      use: host-osx-framework-accelerate
    lapack:
      use: host-osx-framework-accelerate
```

I haven't come up with a better name for `if_needed`, but it's the parameter that allows you to specify how to satisfy dependencies, and should only be resolved by HashDist when resolving dependencies _not_ specified in the profile.

A few examples:
1. User requests numpy on OS X, doesn't specify blas/lapack.  (They get accelerate)
2. User requests lapack on OS X, doesn't specify use flag (They get our lapack)
3. User doesn't request lapack or anything that depends on it (They get nothing)

I know that the second case is a bit funny, but if I default to the `if_needed` choice, I don't have a logical way to override that back to the hashstack lapack package.

Thoughts on naming?  A PR with code will be coming today.
