### ISSUE TITLE
HashDist Enhancement: Profile Hooks

### ISSUE THREAD

**Issue by ahmadia** [hashdist/hashdist#249]
Copied from https://github.com/hashdist/hashdist/pull/244

Developer Alice has created a new Package foo.  foo depends on having a BLAS installed, and she'd like to defer the decision of how to obtain BLAS to somebody that knows more than her about how BLAS is made available on the three major platforms (as well as supercomputers).  She also depends on some other packages, and she knows that these packages are installed slightly differently on different operating systems, so again, she wants somebody with more experience in system builds to ensure those packages are provisioned in the correct manner.  In foo's version control repository, Alice creates a file, stack.yaml.  This file represents her knowledge of foo's dependencies, and works with a specific version of hashstack.  stack.yaml looks something like:

```
extends:
 - name: hashstack
   url: https://github.com/hashdist/hashstack.git
   key: git:1a97d560b12d86d8c36f8e574a1ebb3ea00067b7
   file: common.yaml

packages:
  blas:
  gfortran:
  ipython:
  mpi:
```

So far, Alice has followed the instructions in profile-template.  Her stack.yaml file extends the hashstack/common profile and is anchored to a specific hashstack commit.  Unfortunately, if Alice does not specify an operating system platform, neither she nor anybody else using this file can take advantage of the knowledge the various hashstack developers have assembled about provisioning a common BLAS package across operating systems.

Up until now, we have asked Alice to explicitly extend from a given operating system profile for each operating system she would like to support.  Correspondingly, her users must choose an operating system when installing this profile.

We don't want to take away the ability of users to make this decision for themselves.  My initial proposal was to put some common system-level decisions in each user's ~/config.yaml file.  Ondrej and Dag rightly point out the danger in this.  _The profile-level decision-making machinery is not under version control_, and somebody working from a different install of hashdist may not have these default decisions, or worse, have an out-of-set state of defaults.

So _profile-level decisions should be versioned_, and the logical repository to  put them in is hashstack, because it is already versioned.  Here, again, we must be careful.  We use `when` clauses in the package documents to make decisions based on parameters set in the profiles, but there is no equivalent machinery for making decisions about settings parameters in the profiles.
## Profile Hooks

In the same way that we use Python build stage hooks, I propose that we create profile-hook files that can emit partial profile documents to make programmatic decisions about how to build a profile.  Let's see how this would work for Alice.  Her code remains the same, instead we modify how `common.yaml` behaves.  Here's what `common.yaml` looks like now.

```
FILE: common.yaml
package_dirs:
- pkgs
- base

hook_import_dirs:
- base

parameters:
  BASH: /bin/bash
  PROLOGUE: | # by default, PROLOGUE is a no-op

  pyver: '2.7'  # as in used in lib/pythonX.Y/site-packages
  python_site_packages_rel: 'lib/python2.7/site-packages'

  python_host_packages: '/usr/lib/python2.7/dist-packages'
  use_python_host_packages: false
```

Let's set the following governing rules for `hook` profile files.  
- Must have the same name as the `.yaml` file they complement
- Must define a static function for each section they want to provide.  
- Cannot redefine a section already defined in the corresponding `.yaml` 

Here, we'd like the parameters section to be defined in `common.py`.  

```
FILE: common.py

import sys

def parameters():
  this = {}
  platform = sys.platform if sys.platform != 'linux2' else 'linux'
  this['platform'] = platform
  ...
  return this

...
```

We also define a `default_use` section in the same file:

```
FILE: common.py

...

def default_use():
  this = {}:
  if sys.platform == 'darwin':
    this['blas'] = 'host-osx-framework-accelerate'
  ...
```

What are the advantages of this approach?  The code for making decisions on the system is now under version control.  I don't like that it's a little non-obvious how to do a non-programmatic build, but Alice could specialize her build either by modifying the contents of `common.py` or by choosing not to inherit from `common.yaml`.  I am open to renaming `common.yaml` to something more obvious, but I would like to actually collapse all of the logic currently in the various operating system profiles into this single file (redundantly, if folks prefer to keep the operating-system/package-manager YAML files around).  

I think the programming effort for providing these limited profile-level hooks will not be too high.  This would remove the need for default profiles, but would still require the `default_use` sections, which I don't think anybody had a problem with.

Thoughts on profile-level hooks as an alternate solution to this?
