### ISSUE TITLE
Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 2

### ISSUE THREAD

**Issue by chvillanuevap** [hashdist/hashdist#317]
I'm trying to build a profile from scratch. I am considering the theoretical situation that a developer has just gotten a new machine, and has just downloaded our code.

The first thing I want him to do is install GCC. To achieve that goal, I included this in the `default.yaml` profile:

```
package:
  gcc:
    sources:
    - key: tar.bz2:eaqmtauvqvvkcp62b4xtur4ujedvp7be
      url: http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2
```

When I run `../hashdist/bin/hit build -j4` from the `hashstack` folder, I get the following error:

```
2015/04/06 11:03:29 - ERROR: [package:run_job] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 2
2015/04/06 11:03:29 - ERROR: [package:run_job] command failed (code=2); raising
```

Inspecting the `build.log` further, I see the following:

```
2015/04/06 11:03:29 - INFO: [package:run_job]    'PWD': u'/home/villanueva/.hashdist/tmp/launcher-wvmh5uvayzv3'}
2015/04/06 11:03:29 - INFO: [package:run_job] cc -g -Os -Wall -Wno-unused-function -o launcher launcher.c
2015/04/06 11:03:29 - INFO: [package:run_job] make: cc: Command not found
2015/04/06 11:03:29 - INFO: [package:run_job] make: *** [launcher] Error 127
```

This tells me that HashDist needs the GCC package to build this launcher. What other dependencies does HashDist have? For example, my `default.yaml` profile extends `linux.yaml`, which has a 'fortran' parameter set to true. Does this mean my installation needs `gfortran` to be already installed? Also, `linux.yaml` extends `config.yaml`, which seems to have a dependency on Python. This is not a big deal, as Python comes pre-installed in virtually all Unix distributions.

My question is: what are the basic components I should assume the machine comes with in order to use HashDist, i.e. GCC, Python, etc.?

**Comment by certik** [comment]
It's not very well documented yet, for now see this thread: https://groups.google.com/d/topic/hashdist/3PvxWc8qa2M/discussion, where I posted detailed instructions how to bootstrap Hashdist using Hashdist. We have fixed our gcc package since then, so here are up to date instructions:

File `hd_base.yaml`:
```
extends:
- file: linux.yaml

packages:

  launcher:
  blas:
    use: lapack
  lapack:
    use: lapack
  mpi:
    use: mpich
  python:
    link: shared
  swig:
    build_with: |
      perl
  ipython:
  nose:
  numpy:
  sphinx:
  scipy:
  sympy:
  gmp:
  matplotlib:
  doxygen:
  breathe:
  gcc:
  git:
  subversion:
  perl:
  pyliblzma:
```

Install it first, this works with very old compilers and Python without lzma. Let me know if you get any errors. This profile will install up-to-date gcc compiler (with all our Hashstack fixes, so that things just work, see https://github.com/hashdist/hashstack/tree/master/pkgs/gcc for details, there is lots of non-trivial work there) as well as Python with all the necessary modules (like lzma) that Hashdist needs. The profile also installs a few other things, that are not necessary (like scipy), you can remove those if you want.

Once it is installed, lookup the profile hash and use it as follows (just reference the installed profile using the hash):
```
extends:
- file: linux.yaml

parameters:
  PROLOGUE: |
    export PATH="/local/certik/bld/profile/bto56eplrk4v/bin:$PATH"; export CC=gcc CXX=g++ FC=gfortran

packages:

  launcher:
  blas:
    use: lapack
  lapack:
    use: lapack
  mpi:
    use: mpich
  python:
    link: shared
  swig:
    build_with: |
      perl
  ipython:
...
```

Let me know if it works.
