### ISSUE TITLE
Build same library with two compilers

### ISSUE THREAD

**Issue by chvillanuevap** [hashdist/hashdist#323]
I want to have the ability to change between compilers when I'm working on the development of my research group's code.

For example, let's say my code has a dependency on the NetCDF4 library. I wish to have two versions of this library, one compiled with OpenMPI and another one compiled with MPICH. For this purpose, I set up two different profiles: `netcdf4.openmpi.yaml` and `netcdf4.mpich.yaml`. `netcdf4.openmpi.yaml` has:

```
packages:
  mpi:
    use: openmpi
  netcdf4:
```

and `netcdf4.mpich.yaml` has:

```
packages:
  mpi:
    use: mpich
  netcdf4:
```

My question is if this will cause a conflict. HashDist will first build NetCDF4 with OpenMPI. Then, with the second profile, can it detect that what I'm requesting is to have it built with MPICH? My doubt arises due to the fact that HashDist may see that NetCDF4 was already built, and then simply ignore the fact that I want the library built with MPICH.

**Comment by chvillanuevap** [comment]
Adding to my previous issue, I tried the following:

```
extends:
- file: linux.yaml

packages:

  # OpenMPI version 1.6.4.
  openmpi:
    sources:
    - key: tar.bz2:idfrcorh25xb5ekys5tbk6pucnleyazn
      url: http://www.open-mpi.org/software/ompi/v1.6/downloads/openmpi-1.6.4.tar.bz2

  mpi:
    use: openmpi
```

I want to build OpenMPI version 1.6.4. The default version in `hashdist/hashstack` is 1.6.5. Then, I want the MPI package to use the OpenMPI library I just built.

When I try to build this profile, I get the following:

```
Downloading http://www.open-mpi.org/software/ompi/v1.6/downloads/openmpi-1.6.4.tar.bz2...
[=========================] 100.0% (10.4MB of 10.4MB) 1.170MB/s ETA 0s  
[openmpi] Building openmpi/lel2dzt65fzo, follow log with:
[openmpi]   tail -f /home/villanueva/.hashdist/tmp/openmpi-lel2dzt65fzo/build.log
Downloading http://www.open-mpi.org/software/ompi/v1.6/downloads/openmpi-1.6.5.tar.bz2...
[=========================] 100.0% (10.4MB of 10.4MB) 0.906MB/s ETA 0s  
[mpi] Building mpi/uypp5r7iktyt, follow log with:
[mpi]   tail -f /home/villanueva/.hashdist/tmp/mpi-uypp5r7iktyt/build.log
[profile] Building profile/qhs7t7upkji5, follow log with:
[profile]   tail -f /home/villanueva/.hashdist/tmp/profile-qhs7t7upkji5/build.log
[ERROR] [Errno 17] File exists in silent_relative_symlink('/home/villanueva/.hashdist/bld/openmpi/lel2dzt65fzo/share/man/man1/orteCC.1', u'/home/villanueva/.hashdist/bld/profile/qhs7t7upkji5/share/man/man1/orteCC.1')
[profile|ERROR] hit command failed: [Errno 17] [Errno 17] File exists in silent_relative_symlink('/home/villanueva/.hashdist/bld/openmpi/lel2dzt65fzo/share/man/man1/orteCC.1', u'/home/villanueva/.hashdist/bld/profile/qhs7t7upkji5/share/man/man1/orteCC.1')

real	12m0.504s
user	16m11.224s
sys	4m56.417s
```

You can see that HashDist built OpenMPI with version 1.6.4; however, the MPI package downloads version 1.6.5. It seems that even though I specify that the package MPI uses the package OpenMPI, it does not default to my specifications, but to the ones from HashStack directory. Furthermore, I get a conflict in the end with `hit command failed: [Errno 17] [Errno 17] File exists in silent_relative_symlink('/home/villanueva/.hashdist/bld/openmpi/lel2dzt65fzo/share/man/man1/orteCC.1', u'/home/villanueva/.hashdist/bld/profile/qhs7t7upkji5/share/man/man1/orteCC.1')`.

What is the correct way to overload packages?
