### ISSUE TITLE
Add better compiler support

### ISSUE THREAD

**Issue by certik** [hashdist/hashdist#328]
Each package should know which compiler is used to build it, by introducing a `compiler` variable in yaml. Essentially, `CC`, `FC` and `CXX` must be properly set for each package (and possibly different values for some packages). This is such a fundamental feature, that `hit` should have support for it. In a sense it is similar to `version` (https://github.com/hashdist/hashdist/issues/327).

`hit compilers` should print a list of available compilers (by looking for all compilers in PATH). E.g. it will list something like `gcc@4.9.2 gcc@4.4.7 intel@14.1.1`.
`hit compiler add/remove/list/info` should allow to modify the list. This will be saved probably in `~/.hashdist`. One will be then by able to specify a specific compiler to be used with each package.

Example (together with #327):
```
python:
  compiler: gcc@4.9.2
  version: 3.2
netcdf4:
  compiler: gcc@4.9.2
netcdf4f:
  compiler: intel
```

The version specification `@` is optional (will use let's say the highest available version of not specified). This is coupled to #327, where one specifies versions of packages.

**Comment by chvillanuevap** [comment]
+1 on this. It is slightly related to #323. Ideally, I would like to see something like this:

```
openmpi:
  compiler: gcc@4.9.2
openmpi:
  compiler: intel
```

In my research group, we build OpenMPI with both GCC and the Intel compiler for development/debugging purposes.

**Comment by certik** [comment]
@chvillanuevap  Do you want to have both libraries installed at the same time in the environment?

**Comment by chvillanuevap** [comment]
Sorry, I got confused. I do need separate profiles.

One profile would point to OpenMPI built with GCC, and another profile would point to OpenMPI built with Intel.

I still second this feature request though. It might prove useful to have the ability to select a specific compiler for a specific package.

**Comment by certik** [comment]
Right, exactly.

**Comment by dagss** [comment]
I think this would be handled nicely by mu and Mark's proposal, it is basically exactly what it does.

**Comment by dagss** [comment]
Sorry, that doesn't cover all of this (like `hit compilers`).

**Comment by dagss** [comment]
@certik Let's move the discussion we're having in #314 over here.

Assuming Hashdist was made capable of building gcc (using host gcc) and then use the built gcc to do the rest, within a single profile specification, do you see a fundamental problem with that? To me it seems it must be more reproducible to specify that, than to . I.e. I want `profile = host + spec`, not `profile = host + <set of other profiles in env while building> + spec`.

(So my proposal is (@certik note the new in_profile)

```
gcc -> host_gcc:  # we want a second version of gcc named host_gcc, syntax proposals welcome
    host: true
    in_profile: false  # Do not create links to it in the profile!, only use while building
gcc:
    host: false
    gcc: gcc_host  # build gcc with host_gcc, instead of recursing and trying to build itself with itself
python:
   gcc: gcc  # this is the default so doesn't need to be specified
```
and I think @certik is saying he prefers that we do not do this, but instead first do this in one profile:
```
gcc:
    host: false
    gcc: gcc_host  # build gcc with host_gcc, instead of recursing and trying to build itself with itself
```
and then build Python using this gcc in another profile.

**Comment by certik** [comment]
Ok, here is one problem with your first proposal:
```
gcc -> host_gcc:  # we want a second version of gcc named host_gcc, syntax proposals welcome
    host: true
    in_profile: false  # Do not create links to it in the profile!, only use while building
gcc:
    host: false
    gcc: gcc_host  # build gcc with host_gcc, instead of recursing and trying to build itself with itself
csympy:
  gcc: gcc
python:
   gcc: gcc  # this is the default so doesn't need to be specified
```
Fail, incompatible C++ runtime libraries. How so? Well, first gmp was build using host_gcc (imagine clang, let's say), then gcc was builld. Then csympy was build with our gcc, but linked with the already built gmp --- fail, as now you are linking two different C++ runtime libraries.

That's why I prefer the second approach. Note that I still want to mix compilers in the same profile --- but the above mixing is invalid. A valid mixing is for example to build C/C++ packages with gcc, and then pure Fortran package with ifort, in the same profile.

**Comment by dagss** [comment]
Right. So we could do

```
gmp -> gmp_for_building_gcc:
    gcc: host_gcc
gcc:
    gcc: host_gcc
    gmp: gmp_for_building_gcc
..
```
and so on, and so forth. At some point I guess it may get silly though, so I guess (if there should indeed be a one-step, reproducible way of doing it) what is *really* needed is a way to compose stacks, so that you could take an entire stack, build it with some parameters, and refer to it in another stack. Really just automating what you are doing.

I'll think about it but I guess your way of doing it will be the right way to do it for some time :)

**Comment by certik** [comment]
And of course, you want to mix and match (i.e. test) many compilers, routinely various versions of gcc, intel, clang (build by us), clang (build by Apple), then also NAG and PGI. I like this yaml specification of various compilers that are available:

https://groups.google.com/d/msg/spack/cOcK75FtmDM/PTKOjXHXozkJ

i.e.:

> here's an example snippet from my 
new ~/.spack/compilers.yaml (which could alternately be in 
$SPACK/etc/spack/compilers.yaml for site-wide configuration): 
```
compilers: 
   chaos_5_x86_64_ib: 
     clang@3.1: 
       cc: /collab/usr/gapps/opnsrc/gnu/dev/lnx-2.12-o/clang-3.0/bin/clang 
       cxx: /collab/usr/gapps/opnsrc/gnu/dev/lnx-2.12-o/clang-3.0/bin/clang++ 
       f77: None 
       fc: None 
     gcc@4.4.7: 
       cc: /usr/bin/gcc 
       cxx: /usr/bin/g++ 
       f77: /usr/bin/gfortran 
       fc: /usr/bin/gfortran 
     gcc@4.6.1: 
       cc: /collab/usr/gapps/opnsrc/gnu/dev/lnx-2.12-o/4.6.1/bin/gcc 
       cxx: /collab/usr/gapps/opnsrc/gnu/dev/lnx-2.12-o/4.6.1/bin/g++ 
       f77: /collab/usr/gapps/opnsrc/gnu/dev/lnx-2.12-o/4.6.1/bin/gfortran 
       fc: /collab/usr/gapps/opnsrc/gnu/dev/lnx-2.12-o/4.6.1/bin/gfortran 
     gcc@4.6.2: 
       cc: /collab/usr/gapps/opnsrc/gnu/dev/lnx-2.12-o/4.6.2/bin/gcc 
       cxx: /collab/usr/gapps/opnsrc/gnu/dev/lnx-2.12-o/4.6.2/bin/g++ 
       f77: /collab/usr/gapps/opnsrc/gnu/dev/lnx-2.12-o/4.6.2/bin/gfortran 
       fc: /collab/usr/gapps/opnsrc/gnu/dev/lnx-2.12-o/4.6.2/bin/gfortran 
```
It's structured like a tree with spacing indicating indention level 
indiciating level.  At the top is always the string 'compilers'.  Next 
levels are the SPACK architectures.  Next level is compiler names, then 
compiler/path pairs.  You can use the string 'all' in place of an 
architecture if you want a compiler to be available everywhere.
