### ISSUE TITLE
Support `local` section in sources: in package YAML files

### ISSUE THREAD

**Issue by dagss** [hashdist/hashdist#341]
There's some pressure in the FEniCS community to allow rapid "developer builds", someting like this:

```
extends:
 - name: hashstack
   urls: ['https://github.com/hashdist/hashstack.git']
   key: 'git:1a97d560b12d86d8c36f8e574a1ebb3ea00067b7'
   file: debian.yaml

parameters:
  platform: windows

packages:
  instant:
    sources:
    - local: /home/dagss/code/instant
  ...
```

We already support overriding `sources`; the needed extra feature is the `local` argument which pulls in code from a local directory and doesn't need a hash.
