### ISSUE TITLE
Diamond inheritance not supported

### ISSUE THREAD

**Issue by johannesring** [hashdist/hashdist#354]
Building `scipy` using the latest `dagss/parameters` branch does not work:

``` console
$ hit build test.scipy.yaml 
[CRITICAL] <unknown location>: Package scipy has diamond inheritance (not supported) on: [u'base_package']
```
The profile `test.scipy.yaml` looks like this:
``` yaml
extends:
- file: linux.yaml  

packages:
  launcher:
  cmake:
  gdbm:
  python:
    link: shared
  zlib:
  bzip2:
  sqlite:
  openssl:
  ncurses:
  readline:
  lapack:
    use: openblas
  scipy:
  numpy:
```
