### ISSUE TITLE
--with-mpi=1 is added to configure line

### ISSUE THREAD

**Issue by davydden** [hashdist/hashdist#355]
i am trying to create a simple build script with
```
extends: [autotools_package]
dependencies:
  build: [mpi, blas, {{build_with}}]

...
- name: configure
  extra: ['--enable-mpi',
          '--enable-shared']
```
`/hit show script` produces reasonable result, however on build there is `--with-mpi=1` added to configure. How can I avoid it?

**Comment by davydden** [comment]
getting more interesting
```
extends: [autotools_package]
dependencies:
  build: [mpi, blas]

sources:
- key: tar.gz:ycrzs42hcrfrixwg66b75lofaikcr4c2
  url: http://p4est.github.io/release/p4est-1.1.tar.gz

defaults:
  relocatable: false

build_stages:

- name: configure
  mode: replace # !!
  handler: bash
  bash: |
    ./configure --prefix=${ARTIFACT} \
                --enable-mpi \
                --enable-shared \
                --disable-vtk-binary \
                BLAS_LIBS=-lblas -llapack
```
gives correct bash `build.sh`
```
set -e
export HDIST_IN_BUILD=yes
./configure --prefix=${ARTIFACT} \
            --enable-mpi \
            --enable-shared \
            --disable-vtk-binary \
            BLAS_LIBS=-lblas -llapack
make -j ${HASHDIST_CPU_COUNT}
make install
rm -f ${ARTIFACT}/lib/*.la
```
on hit build it still tries to use `--with-mpi=1 --with-shared=1 --with-vtk-binary=0 BLAS_LIBS=-lblas -llapack`.
